<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '',
    'Are you sure to delete this item?' => '',
    'Are you sure you want to delete this item?' => '',
    'Cancel' => '',
    'Categories' => '',
    'Category' => '',
    'Category ID' => '',
    'Content' => '',
    'Copy' => '',
    'Create' => '',
    'Create Easy Upload' => '',
    'Created At' => '',
    'Delete' => '',
    'Easy Upload' => '',
    'Easy Uploads' => '',
    'Edit' => '',
    'Exchange' => '',
    'First' => '',
    'Full list' => '',
    'Home' => 'Главная',
    'ID' => '',
    'Last' => '',
    'List All' => '',
    'Meta Description' => '',
    'Name' => '',
    'New' => '',
    'Parent ID' => '',
    'Photo' => '',
    'Photos' => '',
    'Position' => '',
    'Post' => '',
    'Posts' => '',
    'Preview' => '',
    'Publish Status' => '',
    'Relations' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Select' => '',
    'Show Category' => '',
    'Sign in' => 'Ввойти',
    'Sign out' => 'Выйти',
    'Sign up' => 'Регистрация',
    'Surname' => '',
    'Title' => '',
    'Title Seo' => '',
    'Type' => '',
    'Type ID' => '',
    'Types' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'View' => '',
    'Views' => '',
    'You are not permitted to perform the requested operation.' => 'Вам не разрешается выполнять запрошенную операцию.',
    'إنشاء سهلة التحميل' => '',
    'تحميل سهل' => '',
];
