<?php
/**
 * /home/ubuntu/workspace/another.dev/app/front/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var front\models\Post $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin([
		'id' => 'Post',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute category_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'category_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(front\models\Category::find()->all(), 'id', 'title'),
	[
		'prompt' => Yii::t('app', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['category_id'])),
	]
); ?>

<!-- attribute type_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'type_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(front\models\Type::find()->all(), 'id', 'title'),
	[
		'prompt' => Yii::t('app', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['type_id'])),
	]
); ?>

<!-- attribute views -->
			<?php echo $form->field($model, 'views')->textInput() ?>

<!-- attribute publish_status -->
			<?php echo $form->field($model, 'publish_status')->textInput() ?>

<!-- attribute title -->
			<?php echo $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

<!-- attribute title_seo -->
			<?php echo $form->field($model, 'title_seo')->textInput(['maxlength' => true]) ?>

<!-- attribute alias -->
			<?php echo $form->field($model, 'alias')->textInput(['maxlength' => true]) ?>

<!-- attribute preview -->
			<?php echo $form->field($model, 'preview')->textarea(['rows' => 6]) ?>

<!-- attribute content -->
			<?php echo $form->field($model, 'content')->textarea(['rows' => 6]) ?>

<!-- attribute meta_description -->
			<?php echo $form->field($model, 'meta_description')->textarea(['rows' => 6]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('app', 'Post'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
